### ISSUE TITLE
ng-if and window.angular

### ISSUE THREAD

**Issue by f0def** [fergaldoyle/angular.js-ie8-builds#12]
In issue #5 you add (this ok)
```javascript
angular.element(document).find('head').prepend('<!--[if IE 8]><style>.ng-hide {display: none !important;}</style><![endif]-->');
```
please change `angular` to `window.angular`
Above code use `window.angular`:
```javascript
!window.angular.$$csp() && ......
```

**Comment by fergaldoyle** [comment]
Can you elaborate on what problem using `angular` causes instead of  `window.angular` ?

**Comment by f0def** [comment]
I use [webpack](https://github.com/webpack/webpack/) to manage dependencies, variable angular not injected

**Comment by fergaldoyle** [comment]
I use webpack too but would not have angular included in the bundle. angular needs special settings when minifying so if you include it in the bundle, then minify the bundle with the wrong settings, it will break angular.

I usually load angular separately from the bundle, and tell webpack that angular is external to allow you still `require('angular')` within your code.

Webpack config:

    externals: {
        'jquery': 'jQuery',
        'angular': 'angular'
    }

**Comment by f0def** [comment]
my webpack.config:
```javascript
resolve: {
    alias: {
      'angular': path.join(bowerRoot, 'angular/angular'),
    }
},
plugins: [
    new webpack.ProvidePlugin({
      angular: 'angular'
    })
}
```

**Comment by f0def** [comment]
@fergaldoyle what if include angular in the bundle (not separately/external), how then to be?

**Comment by ebrentnelson** [comment]
@fergaldoyle do you do this for all Angular modules then? For example, what's your set up for Angular + ngRoute + webpack? I'm trying to migrate to use webpack but need IE8 support. And the Angular 1.2.28 npm packages don't support commonjs.

**Comment by fergaldoyle** [comment]
The only reason not to include Angular in the bundle is because when you minify the bundle, it will break Angular. You can include modules in the bundle and they minify just fine. You should be able to `require` any module (js file) and as long as Angular is a global, loaded before the bundle, it'll work.

It's best to manually load Angular (i.e. via script tag in your html), then you can:
*  Just assume it exists as a global, and work directly with the `angular` variable
*  Mark it as an external in webpack.config which will allow you `var angular = require('angular');` within your code base (handy if third part modules also need to `require` it)
*  Make use of module shimming

http://webpack.github.io/docs/shimming-modules.html
http://webpack.github.io/docs/library-and-externals.html

Externals is the easiest approach.
